services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpass
      POSTGRES_DB: nestdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nestuser -d nestdb"]
      interval: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: nestuser
      DB_PASSWORD: nestpass
      DB_NAME: nestdb
      JWT_SECRET: mysecret
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "sleep 5 && npm run migration:run && npm run start:dev"

volumes:
  postgres_data:
